[package]
name = "vtorrent-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "vtorrent-node"
path = "src/main.rs"

[dependencies]
vtorrent-core     = { path = "../vtorrent-core" }
vtorrent-script   = { path = "../vtorrent-script" }
vtorrent-p2p      = { path = "../vtorrent-p2p" }
vtorrent-overlay  = { path = "../vtorrent-overlay" }
vtorrent-onion    = { path = "../vtorrent-onion" }
vtorrent-snapshot = { path = "../vtorrent-snapshot" }
# CLI argument parsing
clap              = { version = "4", features = ["derive"] }

# Async runtime
tokio             = { version = "1", features = ["full"] }

# Serialization
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
bincode           = "1"

# Crypto
sha2              = "0.10"
hex               = "0.4"
rand              = "0.8"
secp256k1         = { workspace = true }
ripemd            = { workspace = true }
bs58              = { workspace = true }

# Error handling
thiserror         = "1"
anyhow            = "1"

# Logging
tracing           = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Storage
rusty-leveldb     = { version = "1.0", default-features = false }
