[package]
name = "vtorrent-wallet"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vtorrent-core = { path = "../vtorrent-core" }
vtorrent-node = { path = "../vtorrent-node" }
ripemd = { workspace = true }
bs58 = { workspace = true }
secp256k1 = { workspace = true }
sha2 = { workspace = true }
argon2 = { workspace = true }
chacha20poly1305 = { workspace = true }
totp-rs = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
base32 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = "1"
thiserror = { workspace = true }
zeroize = { workspace = true }
tokio = { workspace = true }
