[package]
name = "vtorrent-p2p"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vtorrent-core     = { path = "../vtorrent-core" }

# Async runtime + networking
tokio             = { version = "1", features = ["full"] }
tokio-util        = { version = "0.7", features = ["codec"] }
bytes             = "1"

# Serialization
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
bincode           = "1"

# Crypto
sha2              = "0.10"
hex               = "0.4"
rand              = "0.8"

# Error handling
thiserror         = "1"
anyhow            = "1"

# Logging
tracing           = "0.1"

# Futures utilities
futures           = "0.3"

# HTTP client for Cloudflare DNS-over-HTTPS bootstrap
reqwest           = { version = "0.11", features = ["blocking", "json"] }
urlencoding       = "2"
