[package]
name = "vtorrent-wallet-service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vtorrent-wallet = { path = "../vtorrent-wallet" }
vtorrent-core = { path = "../vtorrent-core" }
vtorrent-node = { path = "../vtorrent-node" }
vtorrent-btc = { path = "../vtorrent-btc" }
thiserror = { workspace = true }
tokio = { version = "1", features = ["sync"] }
hex = { workspace = true }
bitcoin = { workspace = true }
