//! Script opcodes (subset of Bitcoin Script).

/// Script opcode values.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Opcode {
    // Push data
    Op0          = 0x00,
    OpPushData1  = 0x4c,
    OpPushData2  = 0x4d,
    OpPushData4  = 0x4e,
    Op1Negate    = 0x4f,
    Op1          = 0x51,
    Op2          = 0x52,
    Op3          = 0x53,
    Op4          = 0x54,
    Op5          = 0x55,
    Op6          = 0x56,
    Op7          = 0x57,
    Op8          = 0x58,
    Op9          = 0x59,
    Op10         = 0x5a,
    Op11         = 0x5b,
    Op12         = 0x5c,
    Op13         = 0x5d,
    Op14         = 0x5e,
    Op15         = 0x5f,
    Op16         = 0x60,

    // Flow control
    OpNop        = 0x61,
    OpIf         = 0x63,
    OpNotIf      = 0x64,
    OpElse       = 0x67,
    OpEndIf      = 0x68,
    OpVerify     = 0x69,
    OpReturn     = 0x6a,

    // Stack
    OpToAltStack   = 0x6b,
    OpFromAltStack = 0x6c,
    OpIfDup        = 0x73,
    OpDepth        = 0x74,
    OpDrop         = 0x75,
    OpDup          = 0x76,
    OpNip          = 0x77,
    OpOver         = 0x79,
    OpRoll         = 0x7a,
    OpRot          = 0x7b,
    OpSwap         = 0x7c,
    OpTuck         = 0x7d,
    Op2Drop        = 0x6d,
    Op2Dup         = 0x6e,
    Op3Dup         = 0x6f,
    Op2Over        = 0x70,
    Op2Rot         = 0x71,
    Op2Swap        = 0x72,

    // Splice
    OpSize         = 0x82,

    // Bitwise logic
    OpEqual        = 0x87,
    OpEqualVerify  = 0x88,

    // Arithmetic
    Op1Add         = 0x8b,
    Op1Sub         = 0x8c,
    OpNegate       = 0x8f,
    OpAbs          = 0x90,
    OpNot          = 0x91,
    Op0NotEqual    = 0x92,
    OpAdd          = 0x93,
    OpSub          = 0x94,
    OpBoolAnd      = 0x9a,
    OpBoolOr       = 0x9b,
    OpNumEqual     = 0x9c,
    OpNumEqualVerify = 0x9d,
    OpNumNotEqual  = 0x9e,
    OpLessThan     = 0x9f,
    OpGreaterThan  = 0xa0,
    OpLessThanOrEqual = 0xa1,
    OpGreaterThanOrEqual = 0xa2,
    OpMin          = 0xa3,
    OpMax          = 0xa4,
    OpWithin       = 0xa5,

    // Crypto
    OpRipemd160    = 0xa6,
    OpSha1         = 0xa7,
    OpSha256       = 0xa8,
    OpHash160      = 0xa9,
    OpHash256      = 0xaa,
    OpCodeSeparator = 0xab,
    OpCheckSig     = 0xac,
    OpCheckSigVerify = 0xad,
    OpCheckMultiSig = 0xae,
    OpCheckMultiSigVerify = 0xaf,

    // Timelock
    OpCheckLockTimeVerify = 0xb1,
    OpCheckSequenceVerify = 0xb2,
}

impl Opcode {
    /// Try to parse a byte as an opcode.
    pub fn from_byte(b: u8) -> Option<Self> {
        match b {
            0x00 => Some(Self::Op0),
            0x4c => Some(Self::OpPushData1),
            0x4d => Some(Self::OpPushData2),
            0x4e => Some(Self::OpPushData4),
            0x4f => Some(Self::Op1Negate),
            0x51 => Some(Self::Op1),
            0x52 => Some(Self::Op2),
            0x53 => Some(Self::Op3),
            0x54 => Some(Self::Op4),
            0x55 => Some(Self::Op5),
            0x56 => Some(Self::Op6),
            0x57 => Some(Self::Op7),
            0x58 => Some(Self::Op8),
            0x59 => Some(Self::Op9),
            0x5a => Some(Self::Op10),
            0x5b => Some(Self::Op11),
            0x5c => Some(Self::Op12),
            0x5d => Some(Self::Op13),
            0x5e => Some(Self::Op14),
            0x5f => Some(Self::Op15),
            0x60 => Some(Self::Op16),
            0x61 => Some(Self::OpNop),
            0x63 => Some(Self::OpIf),
            0x64 => Some(Self::OpNotIf),
            0x67 => Some(Self::OpElse),
            0x68 => Some(Self::OpEndIf),
            0x69 => Some(Self::OpVerify),
            0x6a => Some(Self::OpReturn),
            0x6b => Some(Self::OpToAltStack),
            0x6c => Some(Self::OpFromAltStack),
            0x6d => Some(Self::Op2Drop),
            0x6e => Some(Self::Op2Dup),
            0x6f => Some(Self::Op3Dup),
            0x70 => Some(Self::Op2Over),
            0x71 => Some(Self::Op2Rot),
            0x72 => Some(Self::Op2Swap),
            0x73 => Some(Self::OpIfDup),
            0x74 => Some(Self::OpDepth),
            0x75 => Some(Self::OpDrop),
            0x76 => Some(Self::OpDup),
            0x82 => Some(Self::OpSize),
            0x87 => Some(Self::OpEqual),
            0x88 => Some(Self::OpEqualVerify),
            0x8b => Some(Self::Op1Add),
            0x8c => Some(Self::Op1Sub),
            0x8f => Some(Self::OpNegate),
            0x90 => Some(Self::OpAbs),
            0x91 => Some(Self::OpNot),
            0x92 => Some(Self::Op0NotEqual),
            0x93 => Some(Self::OpAdd),
            0x94 => Some(Self::OpSub),
            0x9a => Some(Self::OpBoolAnd),
            0x9b => Some(Self::OpBoolOr),
            0x9c => Some(Self::OpNumEqual),
            0x9d => Some(Self::OpNumEqualVerify),
            0x9e => Some(Self::OpNumNotEqual),
            0x9f => Some(Self::OpLessThan),
            0xa0 => Some(Self::OpGreaterThan),
            0xa1 => Some(Self::OpLessThanOrEqual),
            0xa2 => Some(Self::OpGreaterThanOrEqual),
            0xa3 => Some(Self::OpMin),
            0xa4 => Some(Self::OpMax),
            0xa5 => Some(Self::OpWithin),
            0xa6 => Some(Self::OpRipemd160),
            0xa7 => Some(Self::OpSha1),
            0xa8 => Some(Self::OpSha256),
            0xa9 => Some(Self::OpHash160),
            0xaa => Some(Self::OpHash256),
            0xab => Some(Self::OpCodeSeparator),
            0xac => Some(Self::OpCheckSig),
            0xad => Some(Self::OpCheckSigVerify),
            0xae => Some(Self::OpCheckMultiSig),
            0xaf => Some(Self::OpCheckMultiSigVerify),
            0xb1 => Some(Self::OpCheckLockTimeVerify),
            0xb2 => Some(Self::OpCheckSequenceVerify),
            _ => None,
        }
    }
}
